[package]
name = "cassebrique"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
bevy = "0.12.1"
bevy_prototype_lyon = "0.10.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
