name: Release Binaries

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Install dependencies
        run: |
          # Add any necessary steps to install dependencies
          sudo apt-get install -y libasound2-dev

      - name: Check for version change
        id: version_check
        run: |
          # Check if the version has changed in Cargo.toml
          version_changed=$(git diff HEAD^ HEAD -- Cargo.toml | grep -E '^\+version\s*=')
          echo "::set-output name=version_changed::${version_changed}"

      - name: Build and release
        if: ${{ steps.version_check.outputs.version_changed != '' }}
        run: |
          # Build and release binaries for Linux and Windows
          cargo build --release
          # Add more commands to create and package the binaries as needed

      - name: Create Release
        if: ${{ steps.version_check.outputs.version_changed != '' }}
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/*
          token: ${{ secrets.GITHUB_TOKEN }}
