name: Create Tag on Version Change

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get previous commit version
        id: previous_version
        run: echo "::set-output name=version::$(git show HEAD~1:Cargo.toml | grep version | head -n 1 | cut -d '"' -f 2)"

      - name: Get current commit version
        id: current_version
        run: echo "::set-output name=version::$(grep version Cargo.toml | head -n 1 | cut -d '"' -f 2)"

      - name: Compare versions
        id: compare_versions
        run: |
            if [[ "${{ steps.previous_version.outputs.version }}" != "${{ steps.current_version.outputs.version }}" ]]; then
                echo "Version changed. Creating tag..."
                echo "::set-output name=tag_name::${{ steps.current_version.outputs.version }}"
            else
                echo "Version unchanged. Skipping tag creation."
            fi

            - name: Create tag
                id: create_tag
                if: steps.compare_versions.outputs.tag_name
                run: |
                    git tag ${{ steps.compare_versions.outputs.tag_name }}
                    git push origin ${{ steps.compare_versions.outputs.tag_name }}
