name: Check Version Increase

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get old version
        id: get_old_version
        run: echo "OLD_VERSION=$(git show HEAD~1:Cargo.toml | grep version | head -n 1 | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name: Get new version
        id: get_new_version
        run: echo "NEW_VERSION=$(grep version Cargo.toml | head -n 1 | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name: Check if version increased
        id: check_version
        run: |
          if [[ "$NEW_VERSION" > "$OLD_VERSION" ]]; then
            echo "::set-output name=VERSION_INCREASED::true"
          else
            echo "::set-output name=VERSION_INCREASED::false"
          fi

      - name: Create new tag
        if: ${{ steps.check_version.outputs.VERSION_INCREASED == 'true' }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
